### PR TITLE
Add browser

### LINKED ISSUE #1: Adding STAC Browser catalog section
This website currently has a nonexistent catalog section - for the time being, this could be populated with an instance of STAC Browser pointed to our [STAC catalogs](https://github.com/pangeo-data/pangeo-datastore-stac) (or a modified copy pointing to public versions of the Zarr metadata). I would like to add this functionality, but could use some guidance in moving forward.

Since both this website and STAC Browser are independent Vue sites, it would probably be easier to build and deploy them separately on Netlify. I had a few ideas as to where the STAC Browser source code and STAC catalogs could reside in this case:

- In a branch of this repo
- In a separate repo within this organization
- In a repo outside of this organization (such as the one containing our STAC catalogs)

Additionally, we may not need to host the source code if we are able to `git clone` whatever version of STAC Browser we need within the deployment process.

My main concern is - can we deploy to a subdirectory of the domain (such as `https://pangeo-for.ge/catalog`) from a separate Netlify deployment pipeline? Or do we need to keep this all contained within one Netlify pipeline?

### PR DESCRIPTION
**Pull request by cisaacstern**
Will close #1 when complete

Currently this PR adjusts the routing structure of the app and adds a  STAC Browser instance to the route `/catalog`, all based on https://github.com/stac-utils/stac-index/tree/master/client.

However, there is no server instance providing data to the Browser, so it does not currently render any information. Adding that layer will be the next step.

### CODE REVIEW

**Comment by cisaacstern** [comment]
As of https://github.com/pangeo-forge/pangeo-forge-vue-website/pull/6/commits/2160036b5f3303a450edda683832f106112e90a8, the STAC Browser component (`components/Browse.vue`) can render a STAC Item stored on https://raw.githubusercontent.com/  into HTML and display it on the `/catalog` route of the site:

Screen Shot 2021-07-28 at 10 28 26 AM

Next steps are:
- [x] Explore why only Assets are listed for the current Item, but no Item-level data (e.g. geographic bounding box) is presented. This is presumably a result of an incomplete or incorrectly-formatted STAC object. Presumably, the Item level is where we'll want to display dataset-level metadata such as spatiotemporal extent, properties including data variables, etc. 
- [x] Cross-linking the Item to a Catalog and Collection. This will probably require hard-coding github urls for now.
- [ ] Once a minimally-viable version of this Item is rendered from the manually-written STAC object, replicate it using an automated STAC object build. Then use this tooling to build additional Items for the SWOT project.

**Comment by cisaacstern** [comment]
>  Cross-linking the Item to a Catalog and Collection. This will probably require hard-coding github urls for now.

Completed.

> the Item level is where we'll want to display dataset-level metadata such as spatiotemporal extent, properties including data variables, etc.

Getting this sorted is the next step. Currently, we do get a leaflet map at the Item level, but it renders the root catalog's bounding box (not the Item's, as desired). And, adding another to-do:

- [x] Correct CSS wonkiness 

| Broswer.vue component styles 🥴       | STAC Browser dev server styles  🥇 |
| ----------- | ----------- |
| Screen Shot 2021-07-28 at 1 22 53 PM | Screen Shot 2021-07-28 at 1 54 29 PM       |

**Comment by rabernat** [comment]
This is gorgeous! 🤩 

Now is not the time to get into design detail. However, I imagine that the catalog browser will not have the [hero banner](https://versions.bulma.io/0.7.0/documentation/layout/hero/) that the main landing page has but rather will have a more compact navbar / header.

**Comment by cisaacstern** [comment]
> Correct CSS wonkiness

Completed. Table misalignment seemed to have been a dependency issue, and was resolved by https://github.com/pangeo-forge/pangeo-forge-vue-website/pull/6/commits/b0658c7c5d9183cbcdcdfd775f5ed431e476afd9. The remaining manual style issues were cleaned up in the subsequent two commits. (Styles are not optimized, but at least the page is legible.)

> Explore why only Assets are listed for the current Item, but no Item-level data ... 

The way the STAC Browser is currently configured, it appears that declaring an Item with `"rel": "item"` (as opposed to `"rel": "child"`) at the enclosing Collection level cues rendering with the (correct) Item template. Some further observations:

1. STAC Browser currently renders Item-level [datacube extension](https://github.com/stac-extensions/datacube) properties into the [`MetadataSidebar` component](https://github.com/radiantearth/stac-browser/blob/stac-index/src/components/MetadataSidebar.vue). This is probably not ideal for our use case, as there is not enough space there for the density of information we'll want to convey.
2.  Additional Item-level information tabs can be added relatively easily by copying the example provided in [`AssetTab.vue`](https://github.com/radiantearth/stac-browser/blob/stac-index/src/components/AssetTab.vue). We may want to, for example, add a `DatacubeTab.vue` or possibly an `ExampleNotebookTab.vue`.
    - In the absence of such extra tabs, I've jammed a lot of content into the `AssetTab` which STAC purists would/will likely deem to be a strain on the notion of an Asset. These are here pending finding a better place for them.
3. Items do support datetime ranges, but our only current example Item does not appear to provide datetime information in any known calendar format, so I've added placeholders. (We'll also want to change the `MetadataSidebar`'s description of these fields to eschew using the term "acquisition", which is not accurate in the case of model data.
4. It's not immediately obvious what serves as a good thumbnail image for multidimensional ESM datasets, but I do think it's worth having something to draw the user in. I've provided a few plots for our current example Item, though not sure how we'd automate creating such things (which require a Dask cluster, etc.) at scale.

> ... replicate it using an automated STAC object build. 

Retroactively deeming this to be out-of-scope for this PR.

**Comment by cisaacstern** [comment]
I believe the easiest way to get everyone's perspective on this (especially the UI/UX dimension) is to merge, that way the STAC Browser on the `/catalog` page (marked with an 🚧  "under construction" 🚧 banner to avoid any possible confusion) will be viewable without others having to deploy locally.

The code itself is adapted from the links provided by @m-mohr in https://github.com/pangeo-forge/pangeo-forge-vue-website/issues/1#issuecomment-774929000 and will likely need to change soon anyway, once STAC Browser components are installable directly from npm. (If I understand correctly, this on the STAC Browser roadmap.)

**Pull request merged**
